# Generated by Django 4.2.5 on 2023-09-16 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualdict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concepts',
            name='definition',
            field=models.TextField(default=''),
        ),
    ]
