# Generated by Django 4.2.5 on 2023-09-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualdict', '0005_alter_concepts_exampleimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concepts',
            name='exampleText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
